name: pdf_example
description: Demo for creating a PDF file using dart_pdf package.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  path: ^1.8.1
  dart_pdf:
    path: ../
  


