name: dart_pdf
description: A pure Dart library for creating, reading, structurally editing and securing PDF files. Pages, forms, annotations, metadata, text extraction, merging and digital signatures.
version: 1.0.1
homepage: https://github.com/insinfo/insinfo_dart_pdf

environment:
  sdk: ^3.6.0  

dependencies:  
  pointycastle: ^4.0.0
  asn1lib: ^1.6.5
  intl: '>=0.18.0 <0.21.0'
  xml: ">=6.5.0 <7.0.0"
  crypto: ">=3.0.0 <4.0.0"
  convert: ">=3.0.0 <4.0.0"
  http: ^1.2.1
  elliptic: ^0.3.12
  ninja_asn1: ^2.0.0

dev_dependencies:
  test: ^1.26.3 
  

    
      
      
      

