import 'package:dart_pdf/pdf.dart';

/// Builders for the small, deterministic documents the merge tests run on.
///
/// Fixtures are generated by the library itself so they stay in sync with it
/// and need not be checked into the repository as binaries.
class MergeFixtures {
  /// A document of [pageCount] pages, each carrying a line of text that
  /// identifies it.
  static List<int> text({
    int pageCount = 2,
    String prefix = 'Page',
    Size? size,
  }) {
    final PdfDocument document = PdfDocument();
    if (size != null) {
      document.pageSettings = PdfPageSettings(
        size,
        size.width > size.height
            ? PdfPageOrientation.landscape
            : PdfPageOrientation.portrait,
      );
    }
    final PdfFont font = PdfStandardFont(PdfFontFamily.helvetica, 24);
    for (int i = 0; i < pageCount; i++) {
      document.pages.add().graphics.drawString(
        '$prefix ${i + 1}',
        font,
        brush: PdfBrushes.black,
        bounds: const Rect.fromLTWH(40, 40, 400, 40),
      );
    }
    final List<int> bytes = document.saveSync();
    document.dispose();
    return bytes;
  }

  /// A three page document whose first page links to the third one, and whose
  /// second page carries an external URI link.
  static List<int> links() {
    final PdfDocument document = PdfDocument();
    final PdfFont font = PdfStandardFont(PdfFontFamily.helvetica, 18);
    final List<PdfPage> pages = <PdfPage>[
      document.pages.add(),
      document.pages.add(),
      document.pages.add(),
    ];
    for (int i = 0; i < pages.length; i++) {
      pages[i].graphics.drawString(
        'Target ${i + 1}',
        font,
        brush: PdfBrushes.black,
        bounds: const Rect.fromLTWH(40, 200, 300, 30),
      );
    }
    pages[0].annotations.add(
      PdfDocumentLinkAnnotation(
        const Rect.fromLTWH(40, 40, 200, 30),
        PdfDestination(pages[2], const Offset(0, 0)),
      ),
    );
    pages[1].annotations.add(
      PdfUriAnnotation(
        bounds: const Rect.fromLTWH(40, 40, 200, 30),
        uri: 'https://example.org/',
      ),
    );
    final List<int> bytes = document.saveSync();
    document.dispose();
    return bytes;
  }

  /// A single page document with a text box, a checkbox and a combo box.
  static List<int> form({String fieldPrefix = ''}) {
    final PdfDocument document = PdfDocument();
    final PdfPage page = document.pages.add();
    final PdfTextBoxField textBox = PdfTextBoxField(
      page,
      '${fieldPrefix}name',
      const Rect.fromLTWH(40, 40, 200, 24),
      text: 'Isaque',
    );
    final PdfCheckBoxField checkBox = PdfCheckBoxField(
      page,
      '${fieldPrefix}agree',
      const Rect.fromLTWH(40, 80, 20, 20),
      isChecked: true,
    );
    final PdfComboBoxField comboBox = PdfComboBoxField(
      page,
      '${fieldPrefix}city',
      const Rect.fromLTWH(40, 120, 200, 24),
      items: <PdfListFieldItem>[
        PdfListFieldItem('Rio das Ostras', 'rio'),
        PdfListFieldItem('Macae', 'macae'),
      ],
    );
    document.form.fields
      ..add(textBox)
      ..add(checkBox)
      ..add(comboBox);
    final List<int> bytes = document.saveSync();
    document.dispose();
    return bytes;
  }

  /// A two page document with a two level bookmark tree.
  static List<int> bookmarks() {
    final PdfDocument document = PdfDocument();
    final PdfPage first = document.pages.add();
    final PdfPage second = document.pages.add();
    final PdfFont font = PdfStandardFont(PdfFontFamily.helvetica, 18);
    first.graphics.drawString(
      'Chapter one',
      font,
      brush: PdfBrushes.black,
      bounds: const Rect.fromLTWH(40, 40, 300, 30),
    );
    second.graphics.drawString(
      'Chapter two',
      font,
      brush: PdfBrushes.black,
      bounds: const Rect.fromLTWH(40, 40, 300, 30),
    );
    final PdfBookmark root = document.bookmarks.add('Chapter one');
    root.destination = PdfDestination(first, const Offset(0, 0));
    final PdfBookmark child = root.add('Section 1.1');
    child.destination = PdfDestination(first, const Offset(0, 200));
    final PdfBookmark chapterTwo = document.bookmarks.add('Chapter two');
    chapterTwo.destination = PdfDestination(second, const Offset(0, 0));
    final List<int> bytes = document.saveSync();
    document.dispose();
    return bytes;
  }
}

/// Reopens merged bytes as a document. The caller owns the result.
PdfDocument reopen(List<int> bytes) => PdfDocument(inputBytes: bytes);

/// The text of page [index], as recovered by [PdfTextExtractor].
String pageTextOf(PdfDocument document, int index) {
  return PdfTextExtractor(
    document,
  ).extractText(startPageIndex: index, endPageIndex: index);
}

/// The number of annotations on page [index].
int annotationCountOf(PdfDocument document, int index) =>
    document.pages[index].annotations.count;
