import 'dart:io';
import 'dart:convert';

void main() async {
  await generate(
    'assets/truststore/cadeia_icp_brasil',
    'lib/src/security/chain/generated/icp_brasil_trust_store.dart',
    'icpBrasilTrustStore',
    'ICP-Brasil Root Certificates',
  );

  await generate(
    'assets/truststore/serpro',
    'lib/src/security/chain/generated/serpro_trust_store.dart',
    'serproTrustStore',
    'Serpro Root Certificates',
  );

  await generate(
    'assets/truststore/iti',
    'lib/src/security/chain/generated/iti_trust_store.dart',
    'itiTrustStore',
    'ITI Root Certificates',
  );
}

Future<void> generate(
  String sourceDir,
  String outputPath,
  String varName,
  String description,
) async {
  final dir = Directory(sourceDir);
  if (!dir.existsSync()) {
    print('Directory not found: ${dir.path}');
    return;
  }

  final files = dir.listSync(recursive: true).whereType<File>();
  final StringBuffer buffer = StringBuffer();

  buffer.writeln("/// $description embedded for AOT/Wasm support");
  buffer.writeln("/// Generated by scripts/embed_certificates.dart");
  buffer.writeln("");
  buffer.writeln("const List<String> $varName = [");

  int count = 0;
  for (var file in files) {
    // Basic filter for cert files if mixed content exists
    if (!file.path.endsWith('.crt') && !file.path.endsWith('.pem') && !file.path.endsWith('.cer')) {
       // print('Skipping potential non-cert file: ${file.path}');
       // continue;
    }

    try {
      final bytes = await file.readAsBytes();
      String pem = '';
      
      // Basic check if it's already PEM (starts with -----BEGIN)
      try {
        final content = utf8.decode(bytes);
        if (content.contains('-----BEGIN CERTIFICATE-----')) {
           pem = content.replaceAll('\r\n', '\n').trim();
        } else {
           throw Exception('Not PEM');
        }
      } catch (e) {
        // Assume DER, convert to PEM
        final base64 = base64Encode(bytes);
        pem = '-----BEGIN CERTIFICATE-----\n$base64\n-----END CERTIFICATE-----';
      }

      // Escape the string for Dart
      final escaped = pem.replaceAll('\n', '\\n');
      buffer.writeln("  '$escaped',");
      count++;
    } catch (e) {
      print('Skipping ${file.path}: $e');
    }
  }

  buffer.writeln("];");
  
  final outFile = File(outputPath);
  if (!outFile.parent.existsSync()) {
    outFile.parent.createSync(recursive: true);
  }
  outFile.writeAsStringSync(buffer.toString());
  print('Generated $outputPath with $count certificates.');
}
